name: Tests

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
    - '**.tscn'
    - '**.scn'
    - '**.tres'
    - '**.res'
    - '**.gd'
    - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
    - '**.tscn'
    - '**.scn'
    - '**.tres'
    - '**.res'
    - '**.gd'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: GdUnit4 - Test Runner Action
        uses: mpewsey/gdUnit4-action@v1.1.1
        with:
          godot-version: ['4.2.2']
          godot-net: true
          version: '4.2.5' # GdUnit4 version
          paths: 'res://tests/scripts' # Tests path
          report-name: 'test-results.xml'

