name: Tests

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
    - '**.tscn'
    - '**.scn'
    - '**.tres'
    - '**.res'
    - '**.gd'
    - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
    - '**.tscn'
    - '**.scn'
    - '**.tres'
    - '**.res'
    - '**.gd'
    - '.github/workflows/**'

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        godot-version: ['4.2.2']
        godot-status: ['stable']
        
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    steps:
      - uses: actions/checkout@v2

      - name: GdUnit4 - Test Runner Action
        uses: mpewsey/gdUnit4-action@v1.1.1
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          godot-net: true
          version: 'v4.2.5'
          paths: 'res://tests/scripts' # Tests path
          retries: 3
          report-name: Report_GdUnit4_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}.xml

